[package]
name = "marketh"
version = "0.1.0"
edition = "2021"

[lib]
name = "marketh_rs"

[[bin]]
name = "marketh"
path = "src/main.rs"

[dependencies]
image = "0.24.4"
imageproc = "0.23.0"
num = "0.4"
once_cell = "1.20"
rusttype = "0.9.2"
